name: wolt_modal_sheet
repository: https://github.com/woltapp/wolt_modal_sheet

packages:
  - examples/*
  - . ## This is the root package
  - wolt_di
  - wolt_state_management

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  analyze:
    # DCM will handle static analysis
    exec: dcm analyze .
  format:
    exec: dart format --set-exit-if-changed .
